export const Profile_CharacterCardImage_WIDTH = 150;
export const Profile_CharacterCardImage_HEIGHT = 180;

export const CHARACTER_NAME_MAP: Record<string, string> = {
  IMG1: '아가냥',
  IMG2: '공부하냥',
  IMG3: '주부냥',
  IMG4: '프엔냥',
  IMG5: '벡엔냥',
  IMG6: '해커냥',
  IMG7: 'CEO냥',
  IMG8: '출근냥',
  IMG9: '회사냥',
  IMG10: '빵굽냥',
  IMG11: '옷사냥',
  IMG12: '요리사냥',
  IMG13: '방송하냥',
  IMG14: '게임방송하냥',
  IMG15: '택톡냥',
  IMG16: '의사냥',
  IMG17: '간호사냥',
  IMG18: '약사냥',
  IMG19: '축구냥',
  IMG20: '야구냥',
  IMG21: '농구냥',
  IMG22: '군인냥',
  IMG23: '소방관냥',
  IMG24: '경찰관냥',
  IMG25: '배달하냥',
  IMG26: '주식오르냥',
  IMG27: '장보냥',
  IMG28: '게임하냥',
  IMG29: '빈둥빈둥냥',
  IMG30: 'chill냥',
};
